simpleParser/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include("vacancy.urls", namespace='vacancy')),
]

vacancy/urls.py
from django.urls import path
from .views import IndexPageView, VacancyListView, VacancyDetailView, GenerateDataView

app_name = 'vacancy'
urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('vacancy/', VacancyListView.as_view(), name='vacancy_list'),
    path('vacancy/<int:pk>/', VacancyDetailView.as_view(), name='vacancy_detail'),
    path('generate/', GenerateDataView.as_view(), name='generate'),
]

vacancy/models.py
from django.db import models
from django.urls import reverse


class VacancyModel(models.Model):
    name = models.CharField(max_length=250, verbose_name="Назвние вакансии")
    short_description = models.TextField(verbose_name="Краткое описание вакансии")
    description = models.TextField(verbose_name="Описание вакансии")
    salary_from = models.IntegerField(verbose_name="з/п от", blank=True, null=True)
    salary_to = models.IntegerField(verbose_name="з/п до", blank=True, null=True)
    currency = models.CharField(max_length=4, verbose_name="Валюта з/п", blank=True, null=True)
    link = models.URLField(max_length=60, verbose_name="Ссылка на вакансию")

    class Meta:
        db_table = 'Vacancy'
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

    def get_absolute_url(self):
        return reverse('vacancy:vacancy_detail', args=[self.id])

    def __str__(self):
        return self.name

vacancy/views.py
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from celery.result import AsyncResult
from django.http import JsonResponse
from django.http import Http404

from .models import VacancyModel
from .tasks import generate_vacancy_data


class IndexPageView(TemplateView):
    template_name = "index.html"


class VacancyListView(ListView):
    template_name = "list.html"
    model = VacancyModel


class VacancyDetailView(DetailView):
    template_name = "detail.html"
    model = VacancyModel


class GenerateDataView(TemplateView):
    template_name = "preloader.html"

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            task = AsyncResult(self.request.session.get('task_uuid'))
            return JsonResponse({'task_status': task.state})
        else:
            raise Http404

    def post(self, request, *args, **kwargs):
        task = generate_vacancy_data.delay()
        self.request.session['task_uuid'] = task.id
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

vacancy/templates/detail.html
{% extends "index.html" %}

{% block content %}
  <h3>{{ object.name }}</h3>
  <p><b>Short description: </b>{{ object.short_description }}</p>
  <p><b>Description: </b>{{ object.description }}</p>
  <p><b>Salary from: </b>{{ object.salary_from }}</p>
  <p><b>Salary to: </b>{{ object.salary_to }}</p>
  <p><b>Currency: </b>{{ object.currency }}</p>
  <p><b>Link: </b><a href="{{ object.link }}">{{ object.link }}</a></p>
{% endblock %}

vacancy/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Kodeks vacancy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
    <div class="container">
    {% block content %}
        <form action="{% url 'vacancy:generate' %}" method="post">{% csrf_token %}
            <input class="btn btn-outline-primary btn-lg" type="submit" value="Сбор данных"/>
        </form>
    {% endblock %}

    {% block add_js %}{% endblock %}
    </div>
</body>
</html>

vacancy/templates/list.html
{% extends "index.html" %}

{% block content %}
    <ul class="list-group">
    {% for vacancy in object_list %}
      <li class="list-group-item">
          <h2><a href="{{ vacancy.get_absolute_url }}">{{ vacancy.name }}</a></h2>
      </li>
    {% empty %}
        <h2>Данные отсутствуют!</h2>
    {% endfor %}
    </ul>
{% endblock %}

vacancy/templates/preloader.html
{% extends "index.html" %}
{% load staticfiles %}

{% block content %}
    <div align="center">
        <h1>Идет загрузка данных</h1>
        <h3>Пожалуйста подождите ....</h3>
    </div>
{% endblock %}

{% block add_js %}
    <script type="text/javascript" src="{% static 'js/preloader.js' %}"></script>
{% endblock %}